version: 2
jobs:
  go_get:
    docker:
      - image: cimg/go:1.16
    steps:
      - run:
          name: Test go get
          command: |
            go get github.com/DeNA/unity-meta-check
      - run:
          name: Test
          command: unity-meta-check --version

workflows:
  version: 2

  main:
    jobs:
      - go_get:
          filters:
            branches:
              only: master
