version: 2
jobs:
  go_get:
    docker:
      - image: cimg/go:1.16
    steps:
      - run:
          name: Test go get
          command: |
            go get github.com/DeNA/unity-meta-check
      - run:
          name: Test
          command: unity-meta-check --version

  test-linux:
    docker:
      - image: cimg/go:1.16

    steps:
      - checkout
      - run:
          name: Test on Linux
          command: |
            git submodule update --init --recursive
            go test -v ./...

workflows:
  version: 2

  test-linux-and-go-get:
    jobs:
      - test-linux
      - go_get:
          filters:
            branches:
              only: master
