version: 2
jobs:
  go_get:
    docker:
      - image: cimg/go:1.14
    steps:
      - run:
          name: Test go get
          command: |
            git config --global url."git@github.com:".insteadOf "https://github.com/"
            ssh -T -oStrictHostKeyChecking=no git@github.com || true

            go get github.com/DeNA/unity-meta-check
      - run:
          name: Test
          command: unity-meta-check --version

  build-linux:
    docker:
      - image: cimg/go:1.14

    steps:
      - checkout
      - run:
          name: Test on Linux
          command: |
            git submodule update --init --recursive
            go test -v ./...

  build-windows:
    resource_class: windows.medium
    machine:
      image: windows-default

    steps:
      - checkout
      - run:
          name: Test on Windows
          command: |
            git submodule update --init --recursive
            go test -v ./...
          shell: bash.exe

workflows:
  version: 2

  build-linux-and-windows:
    jobs:
      - build-linux
      - build-windows
      - go_get:
          filters:
            branches:
              only: master
