#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.."; pwd)"


has() {
	local cmd="$1"
	which "$cmd" >/dev/null 2>&1
}


echo-stderr() {
	local message="$*"
	printf "%s\n" "$message" 1>&2
}


throw() {
	local message="$*"
	echo-stderr "error: $message"
	false
}


usage() {
	cat - 1>&2 <<-EOS
usage: deploy-gh-release [<options>]

OPTIONS
	-h, --help    print this usage
EOS
}


usage-error() {
	local message="$*"
	echo-stderr "$message"
	usage
	false
}


main() {
	local version
	version="$("$BASE_DIR/scripts/print-version")"

	gh --version || throw "gh must be available (see https://cli.github.com/)"
	gh auth status

	local nproc=1
	if has sysctl; then
		nproc="$(sysctl -n hw.logicalcpu)"
	fi
	if has nproc; then
		nproc="$(nproc)"
	fi

	(cd "$BASE_DIR"
		local title
		title="$(git log -1 --format=%s HEAD)"

		local tag="v${version}"

		(git tag | grep -Fqx "$tag") || throw "tag does not exist: '$tag'"
		git push origin "$tag" || throw "a tag has the same name exists, so if still you want to overwrite the tag, please remove the tag on the remote and try again."

		echo-stderr "ENVIRONMENT"
		echo-stderr "revision to deploy:\n$(git rev-parse HEAD)\n"
		echo-stderr "go version:\n$(go version)\n"

		git checkout "$tag" || throw "make git status clean and try again."

		echo-stderr "DEPLOY TO GITHUB RELEASES"
		echo-stderr "creating a github release if it does not exist..."

		if ! gh release view "$tag"; then
			if echo "$version" | "$BASE_DIR/scripts/is-prerelease"; then
				gh release create --prerelease --title "$title" "$tag"
			else
				gh release create --title "$title" "$tag"
			fi
		fi
		echo-stderr
		
		echo-stderr "building executables..."
		make -j"$nproc" clean all
		echo-stderr

		[[ -d "./out" ]] || throw "cannot find the generated distribution dir: '${BASE_DIR}/out'"

		echo-stderr "uploading executables..."
		(cd "./out"
			find . -type f | sed 's/\.\///' | xargs gh release upload "$tag"
		)

		gh release view -w "$tag"
	)
}


case "$*" in
	--help | -h)
		usage
		false ;;
	*)
		main "$@" ;;
esac
