#!/bin/bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")/.."; pwd)"
CIRCLECI_IMAGE='docker.pkg.github.com/dena/unity-meta-check/unity-meta-check-circleci'
IMAGE='docker.pkg.github.com/dena/unity-meta-check/unity-meta-check-v2'


usage() {
	cat - 1>&2 <<-EOS
usage: push-image [<options>]

OPTIONS
	-h, --help    print this usage
	--latest      also push latest
EOS
}


main() {
	local arg="${1:-}"
	if [[ "$arg" == "-h" || "$arg" == "--help" || "$arg" == "help" ]]; then
		usage
		false
	fi

	(cd "$BASE_DIR"
		local version
		version="$("$BASE_DIR/scripts/print-version")"

		docker push "$IMAGE:$version"
		if [[ "$arg" == "--latest" ]]; then
			docker push "$IMAGE:latest"
		fi

		docker push "$CIRCLECI_IMAGE:$version"
		if [[ "$arg" == "--latest" ]]; then
			docker push "$CIRCLECI_IMAGE:latest"
		fi
	)
}


main "$@"
