name: Release

on:
  push:
    branches:
      - "master"
    tags:
      - "v*"

jobs:
  build-and-push:
    name: Build and push container image
    runs-on: ubuntu-latest
    permissions:
      contents: read

    strategy:
      matrix:
        images:
          - dockerfile: ./build.Dockerfile
            image_name: ghcr.io/dena/unity-meta-check/unity-meta-check-builder
          - dockerfile: ./Dockerfile
            image_name: ghcr.io/dena/unity-meta-check/unity-meta-check
          - dockerfile: ./.github/images/Dockerfile
            image_name: ghcr.io/dena/unity-meta-check/unity-meta-check-gh-action
          - dockerfile: ./.circleci/images/Dockerfile
            image_name: ghcr.io/dena/unity-meta-check/unity-meta-check-circleci

    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: recursive

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Build and push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.images.dockerfile }}
          tags: ${{ matrix.images.image_name }}:latest
          push: true

      - name: Add version tag
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.images.dockerfile }}
          tags: ${{ matrix.images.image_name }}:${{ github.ref_name }}
          push: true
